<?php
// Start session if not already started
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Ensure database config is loaded
require_once dirname(__DIR__) . '/config.php';

// Sync current page name
$current_page = basename($_SERVER['SCRIPT_NAME']);

// Set path to root for public pages
if (!isset($path_to_root)) {
    $path_to_root = './';
}
// Ensure path_to_root ends with a forward slash
$path_to_root = rtrim($path_to_root, '/\\') . '/';
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Performance: Preconnect to critical origins -->
  <link rel="preconnect" href="https://cdn.jsdelivr.net" crossorigin>
  <link rel="preconnect" href="https://cdnjs.cloudflare.com" crossorigin>
  <link rel="preconnect" href="https://fonts.googleapis.com" crossorigin>
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="preconnect" href="https://www.googletagmanager.com" crossorigin>
  <link rel="dns-prefetch" href="https://unpkg.com">
  <link rel="dns-prefetch" href="https://fcm.googleapis.com">

  <!-- Favicon -->
  <link rel="icon" href="tech.png" type="image/png" />
  <link rel="apple-touch-icon" href="tech.png">
  <link rel="shortcut icon" href="tech.png" type="image/png">

  <!-- Stylesheets -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
  <!-- Google Fonts - Plus Jakarta Sans & Outfit -->
  <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&family=Outfit:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <!-- SEO Meta Tags (generated by seo_helper.php) -->
  <?php require_once __DIR__ . '/seo_helper.php'; ?>

  <!-- Google Tag Manager -->
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-P7RP5TLZ');</script>
  <!-- End Google Tag Manager -->

  <!-- Shared CSS Variables & Public Navigation Layout Styles -->
  <link href="<?= $path_to_root ?>assets/css/header.css?v=2" rel="stylesheet">
  <style>
    :root {
      --color-primary-dark: #00264d;
      --color-secondary-dark: #0f3a5d;
      --color-accent: #c45827;
      --color-orange: #ff6600;
      --color-orange-hover: #e65c00;
      --color-bg-body-tertiary: #f8f9fa;
      --color-bg-box: #f1f1f1;
      --color-bg-box-hover: #e0ebf5;
      --color-white: #ffffff;
      --color-text-body: #333;
      --color-text-link: #00264d;
      --color-text-light: #a8b2c1;
      --color-shadow: rgba(0, 0, 0, 0.05);
      --color-overlay: rgba(0, 0, 0, 0.5);
      --color-service-bg: #f9fafc;
      --color-service-hover: #eaf2fa;
      --color-border-muted: #ccc;
      --color-input-bg: transparent;
      --color-input-text: #f1f5f9;
      --color-input-border: #64748b;
      --color-info: #38bdf8;
      
      /* Premium UI/UX Tokens */
      --shadow-soft: 0 10px 40px -10px rgba(0,0,0,0.08);
      --shadow-hover: 0 20px 50px -10px rgba(0,0,0,0.12);
      --transition-smooth: all 0.4s cubic-bezier(0.16, 1, 0.3, 1);
    }

    /* Typography & Core */
    body {
      font-family: 'Inter', 'Segoe UI', sans-serif;
      background-color: var(--color-bg-body-tertiary);
      line-height: 1.7;
    }
    
    .py-6 {
      padding-top: 5rem !important;
      padding-bottom: 5rem !important;
    }
    
    h1, h2, h3, h4, h5, h6 {
      font-family: 'Plus Jakarta Sans', sans-serif;
      letter-spacing: -0.02em;
    }

    /* Scroll Reveal Animations */
    .reveal-up {
      opacity: 0;
      transform: translateY(40px);
      transition: var(--transition-smooth);
    }
    .reveal-up.active {
      opacity: 1;
      transform: translateY(0);
    }
    
    .reveal-fade {
      opacity: 0;
      transition: var(--transition-smooth);
    }
    .reveal-fade.active {
      opacity: 1;
    }

    /* Dropdown Hover Logic for Desktop */
    @media (min-width: 992px) {
      .dropdown-hover:hover > .dropdown-menu {
        display: block;
        margin-top: 0;
        animation: fadeIn 0.2s ease-in-out;
      }
    }
    @keyframes fadeIn {
      from { opacity: 0; transform: translateY(5px); }
      to { opacity: 1; transform: translateY(0); }
    }

    /* Preloader */
    .preloader {
      position: fixed;
      top: 0; left: 0; width: 100%; height: 100vh;
      background: #020617;
      display: flex; flex-direction: column; justify-content: center; align-items: center;
      z-index: 999999;
      opacity: 1;
      transition: opacity 0.4s cubic-bezier(0.4, 0, 0.2, 1);
    }
    .preloader.fade-out {
      opacity: 0;
      pointer-events: none;
    }
    .loader-container {
      position: relative;
      display: flex; justify-content: center; align-items: center;
      width: 150px; height: 150px;
      margin-bottom: 1.5rem;
    }
    .loader-glow {
      position: absolute; width: 85px; height: 85px; border-radius: 50%;
      background: radial-gradient(circle, rgba(225, 85, 1, 0.2) 0%, rgba(10, 45, 94, 0.3) 100%);
      filter: blur(15px);
      animation: corePulse 2s ease-in-out infinite alternate;
    }
    .loader-outer-ring {
      position: absolute; width: 120px; height: 120px; border-radius: 50%;
      border: 3px solid transparent; border-top-color: #0A2D5E; border-bottom-color: #0A2D5E;
      animation: spinClockwise 1.5s cubic-bezier(0.5, 0.1, 0.4, 0.9) infinite;
    }
    .loader-inner-ring {
      position: absolute; width: 90px; height: 90px; border-radius: 50%;
      border: 3px solid transparent; border-left-color: #E15501; border-right-color: #E15501;
      animation: spinCounterClockwise 1.2s cubic-bezier(0.5, 0.1, 0.4, 0.9) infinite;
    }
    @keyframes spinClockwise { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
    @keyframes spinCounterClockwise { 0% { transform: rotate(0deg); } 100% { transform: rotate(-360deg); } }
    @keyframes corePulse { 0% { transform: scale(0.9); opacity: 0.5; } 100% { transform: scale(1.15); opacity: 0.9; } }



    /* Header CSS moved to assets/css/header.css */
    /* Shared visible footer styles */
    .footer-section {
      background: #091a36;
      color: #cbd5e1;
      padding: 5rem 0 2rem;
      font-size: 0.9rem;
      position: relative;
      overflow: hidden;
      z-index: 1;
      border-top: 1px solid rgba(255, 255, 255, 0.05);
    }
    .cloud-svg {
      position: absolute; pointer-events: none; z-index: 0; opacity: 0.08;
    }
    .cloud-top-left { top: 10px; left: 0; width: 180px; }
    .cloud-center { top: 50%; left: 50%; transform: translate(-50%, -50%); width: 260px; opacity: 0.04; }
    .cloud-bottom-right { bottom: 10px; right: 0; width: 200px; opacity: 0.06; }
    .cloud-svg svg { display: block; width: 100%; height: auto; }
    
    .footer-grid {
      display: grid; grid-template-columns: 1fr; gap: 2.5rem; position: relative; z-index: 2;
    }
    @media (min-width: 576px) {
      .footer-grid { grid-template-columns: repeat(2, 1fr); }
    }
    @media (min-width: 992px) {
      .footer-grid { grid-template-columns: 2.5fr 2fr 2fr 2.5fr; gap: 3rem; }
    }
    .footer-col h5 {
      color: #ffffff; font-size: 1.05rem; font-weight: 700; margin-bottom: 1.5rem;
      position: relative; padding-bottom: 0.5rem; text-transform: uppercase; letter-spacing: 0.05em;
    }
    .footer-col h5::after {
      content: ''; position: absolute; bottom: 0; left: 0; width: 35px; height: 2px; background-color: #ff6600;
    }
    .footer-col p { color: #94a3b8; line-height: 1.7; margin-bottom: 1rem; }
    
    .footer-links-list { list-style: none; padding: 0; margin: 0; }
    .footer-links-list li { margin-bottom: 0.75rem; }
    .footer-links-list a {
      color: #94a3b8; text-decoration: none; transition: all 0.2s ease; display: inline-flex; align-items: center; gap: 0.5rem;
    }
    .footer-links-list a::before {
      content: '→'; color: #ff6600; opacity: 0; transition: all 0.2s ease; transform: translateX(-5px);
    }
    .footer-links-list a:hover { color: #ffffff; padding-left: 0.5rem; }
    .footer-links-list a:hover::before { opacity: 1; transform: translateX(0); }
    
    .footer-contact-info { list-style: none; padding: 0; margin: 0; }
    .footer-contact-info li { display: flex; align-items: flex-start; gap: 0.75rem; color: #94a3b8; margin-bottom: 0.85rem; font-size: 0.88rem; }
    .footer-contact-info li i { color: #ff6600; margin-top: 0.25rem; width: 16px; text-align: center; }
    .footer-contact-info li a { color: #94a3b8; text-decoration: none; transition: color 0.2s ease; }
    .footer-contact-info li a:hover { color: #ffffff; }
    
    .social-icons { margin-top: 1.5rem; display: flex; gap: 0.75rem; }
    .social-icons a {
      width: 36px; height: 36px; background: rgba(255, 255, 255, 0.05); border: 1px solid rgba(255, 255, 255, 0.1);
      color: #ffffff; border-radius: 50%; display: inline-flex; align-items: center; justify-content: center;
      font-size: 1rem; transition: all 0.3s ease;
    }
    .social-icons a:hover {
      background: #ff6600; border-color: #ff6600; color: #ffffff; transform: translateY(-3px);
      box-shadow: 0 5px 15px rgba(255, 102, 0, 0.3);
    }
    .newsletter-form { display: flex; flex-direction: column; gap: 0.75rem; }
    .newsletter-form input[type="email"] {
      background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.1);
      padding: 0.75rem 1rem; color: #ffffff; font-size: 0.88rem; border-radius: 8px; outline: none; transition: all 0.2s ease;
    }
    .newsletter-form input[type="email"]:focus { border-color: #ff6600; box-shadow: 0 0 0 3px rgba(255, 102, 0, 0.15); }
    .newsletter-form button {
      background: #ff6600; color: #ffffff; border: none; padding: 0.75rem 1rem;
      font-size: 0.88rem; font-weight: 700; border-radius: 8px; cursor: pointer; transition: all 0.2s ease;
    }
    .newsletter-form button:hover { background: #e65c00; transform: translateY(-1px); }
    .footer-bottom {
      border-top: 1px solid rgba(255, 255, 255, 0.05); padding-top: 1.5rem; margin-top: 4rem;
      font-size: 0.82rem; color: #64748b; text-align: center;
    }
    @media (min-width: 768px) {
      .cloud-top-left { width: 240px; }
      .cloud-center { width: 320px; }
      .cloud-bottom-right { width: 260px; }
    }
    /* Mobile responsive rules moved to assets/css/header.css */
      .unique-sidebar .nav-link { font-size: 0.88rem; padding: 0.6rem 0.8rem; }
    }
    #backToTop {
      position: fixed; bottom: 30px; right: 25px; background-color: var(--color-orange); color: white;
      padding: 12px 15px; border-radius: 50px; font-size: 1.2rem; z-index: 999; display: none;
      transition: opacity 0.3s ease, transform 0.3s ease; box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
    }
    #backToTop:hover { background-color: var(--color-orange-hover); transform: translateY(-4px); }
  </style>

  <!-- Firebase Client-Side Scripts -->
  <?php
  $fbLoader = (isset($path_to_root) ? $path_to_root : './') . 'includes/firebase_js.php';
  if (file_exists($fbLoader)) {
      include $fbLoader;
  }
  ?>
</head>
<body>

<?php 
// Include ads and notifications system
if (file_exists($path_to_root . 'includes/ad_placer.php')) include $path_to_root . 'includes/ad_placer.php';
if (file_exists($path_to_root . 'includes/ad_system.php')) include $path_to_root . 'includes/ad_system.php';
?>

  <!-- Preloader -->
  <div class="preloader">
    <div class="loader-container">
      <div class="loader-glow"></div>
      <div class="loader-outer-ring"></div>
      <div class="loader-inner-ring"></div>
      <span class="text-white font-monospace mb-0" style="z-index: 10; font-weight: 900; letter-spacing: 2px; font-size: 1.1rem;">WQS</span>
    </div>
  </div>

  <div class="main-content">
    
<?php if(empty($hide_header_footer)): ?>
    <!-- Shared Glassmorphic Header Navbar -->
    <header class="main-header">
      <div class="container d-flex justify-content-between align-items-center">
        <div class="navbar-brand">
          <a href="index.php"><img src="tech.png" alt="Wise Quotient Soft" /></a>
        </div>

        <!-- Navigation items -->
        <div class="d-flex align-items-center gap-3">
          <nav class="d-none d-md-block">
            <ul class="nav">
              <li class="nav-item"><a class="nav-link <?= ($current_page === 'index.php') ? 'active' : '' ?>" href="index.php">Home</a></li>
              <li class="nav-item"><a class="nav-link <?= ($current_page === 'services.php') ? 'active' : '' ?>" href="services.php">Services</a></li>
              <li class="nav-item"><a class="nav-link <?= ($current_page === 'portforlio.php' || $current_page === 'portfolio.php') ? 'active' : '' ?>" href="portforlio.php">Portfolio</a></li>
              <li class="nav-item"><a class="nav-link <?= ($current_page === 'free_packages.php') ? 'active' : '' ?>" href="free_packages.php"><i class="fas fa-gift text-orange me-1"></i>Free Packages</a></li>
              <li class="nav-item"><a class="nav-link <?= ($current_page === 'scholarships.php' || $current_page === 'scholarship.php' || $current_page === 'scholarship_apply.php' || $current_page === 'scholarship_track.php') ? 'active' : '' ?>" href="scholarships.php"><i class="fas fa-graduation-cap me-1"></i>Scholarships</a></li>
              
              <li class="nav-item dropdown dropdown-hover">
                <a class="nav-link dropdown-toggle <?= (in_array($current_page, ['about.php', 'team.php', 'blog.php', 'contact.php'])) ? 'active' : '' ?>" href="#" id="companyDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Company
                </a>
                <ul class="dropdown-menu border-0 shadow-lg rounded-4" aria-labelledby="companyDropdown">
                  <li><a class="dropdown-item py-2 fw-semibold <?= ($current_page === 'about.php') ? 'active text-orange' : 'text-body' ?>" href="about.php">About Us</a></li>
                  <li><a class="dropdown-item py-2 fw-semibold <?= ($current_page === 'team.php') ? 'active text-orange' : 'text-body' ?>" href="team.php">Team</a></li>
                  <li><a class="dropdown-item py-2 fw-semibold <?= ($current_page === 'blog.php') ? 'active text-orange' : 'text-body' ?>" href="blog.php">Blog</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item py-2 fw-semibold <?= ($current_page === 'contact.php') ? 'active text-orange' : 'text-body' ?>" href="contact.php">Contact</a></li>
                </ul>
              </li>
            </ul>
          </nav>

          <!-- Search button icon -->
          <button class="btn border-0 bg-transparent p-0" onclick="toggleSearchBar()" aria-label="Search">
            <i class="fas fa-search text-body fs-5"></i>
          </button>

          <!-- Mobile Sidebar Hamburger bar toggler -->
          <button class="hamburger" id="hamburgerBtn" aria-label="Toggle Menu">
            <i class="fas fa-bars text-body fs-4"></i>
          </button>

          <!-- CTA login actions -->
          <div class="d-none d-md-flex gap-2">
            <a href="login.php" class="btn btn-outline-dark-text">Login</a>
            <a href="register.php" class="btn btn-orange">Signup</a>
          </div>
        </div>
      </div>

      <!-- Shared Search Panel overlay -->
      <div id="searchPanel" class="search-panel"> 
        <div class="container py-4">
          <form action="search.php" method="GET" class="w-100">
            <div class="d-flex justify-content-between align-items-center mb-4">
              <div class="input-group">
                <button type="submit" class="input-group-text bg-transparent border-0 text-body"><i class="fas fa-search"></i></button>
                <input type="text" name="q" id="headerSearchInput" class="form-control border-0 shadow-none text-body" placeholder="Search services, portfolio, or leadership team..." autocomplete="off" required />
              </div>
              <button type="button" class="btn bg-transparent border-0 fs-3" onclick="toggleSearchBar()" aria-label="Close Search">
                <i class="fas fa-times"></i>
              </button>
            </div>
          </form>
          
          <!-- Live search results container -->
          <div id="liveSearchResults" class="mt-4" style="display: none;">
            <h5 class="fw-bold mb-3">Instant Results</h5>
            <div id="liveSearchResultsList" class="list-group list-group-flush border-0">
              <!-- Live search items load dynamically -->
            </div>
          </div>

          <!-- Default topics container -->
          <div id="defaultSearchTopics">
            <h5 class="fw-bold mb-3">Trending Topics</h5>
            <ul class="list-unstyled text-muted">
              <li class="mb-2">Intelligent Systems</li>
              <li class="mb-2">AI + Automation</li>
              <li class="mb-2">Custom SaaS Development</li>
              <li class="mb-2">Digital Strategy</li>
              <li class="mb-2">Innovation Architecture</li>
            </ul>
          </div>
        </div>
      </div>
    </header>

    <!-- Mobile Navigation Sidebar -->
    <div class="unique-sidebar" id="uniqueSidebar" onclick="event.stopPropagation()">
      <a class="nav-link <?= ($current_page === 'index.php') ? 'active' : '' ?>" href="index.php">Home</a>
      <a class="nav-link <?= ($current_page === 'services.php') ? 'active' : '' ?>" href="services.php">Services</a>
      <a class="nav-link <?= ($current_page === 'about.php') ? 'active' : '' ?>" href="about.php">About Us</a>
      <a class="nav-link <?= ($current_page === 'team.php') ? 'active' : '' ?>" href="team.php">Team</a>
      <a class="nav-link <?= ($current_page === 'portforlio.php' || $current_page === 'portfolio.php') ? 'active' : '' ?>" href="portforlio.php">Portfolio</a>
      <a class="nav-link <?= ($current_page === 'free_packages.php') ? 'active' : '' ?>" href="free_packages.php"><i class="fas fa-gift text-orange me-1"></i>Free Packages</a>
      <a class="nav-link <?= ($current_page === 'blog.php') ? 'active' : '' ?>" href="blog.php">Blog</a>
      <a class="nav-link <?= ($current_page === 'scholarships.php' || $current_page === 'scholarship.php' || $current_page === 'scholarship_apply.php' || $current_page === 'scholarship_track.php') ? 'active' : '' ?>" href="scholarships.php"><i class="fas fa-graduation-cap me-1"></i>Scholarships</a>
      <a class="nav-link <?= ($current_page === 'contact.php') ? 'active' : '' ?>" href="contact.php">Contact</a>
      
      <div class="mt-4 d-flex flex-column gap-2 px-3">
        <a href="login.php" class="btn btn-outline-light rounded-pill w-100 py-2">Login</a>
        <a href="register.php" class="btn btn-orange rounded-pill w-100 py-2">Signup</a>
      </div>
    </div>
<?php endif; ?>

    <!-- Mobile Bottom Tab Navigation is rendered in public_footer.php -->

